### ISSUE TITLE
Ruby on Rails Installation Issues

### ISSUE THREAD

**Issue by injones27** [learn-co-curriculum/phase-0-wsl2-env-ruby#12]
### Canvas Link

https://learning.flatironschool.com/courses/6601/pages/windows-wsl2-ruby-installation?module_item_id=510624

### Concern

I've tried at least 20x to install Ruby 2.7.4 using Ubuntu and it continues to say ruby 2.7.4 is not existent. It doesn't show in my "rvm list known" command results. 

All I get is, "Error running '__rvm_make -j4' " and, "There has been an error while running make. Halting the installation."

![Error Ruby](https://user-images.githubusercontent.com/62906937/209500403-93669fc4-cb0b-4165-9a0f-a6fe15b2f599.PNG)

**Comment by lizbur10** [comment]
Hi @injones27!

Thanks for raising this issue. Based on your description, it sounds like the
issue may be related to your environment setup rather than with the lesson
itself or the instructions. The curriculum team monitors these issues so that we
can fix typos and bugs in the curriculum, but we aren't equipped to provide
support.

To get help with your question, you should either:

- Reach out to your instructor (if you've started the program and have an
  instructor)
- Use the
  [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit)
  feature in Canvas to connect with a Technical Coach on the Academic Success
  Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
